# site properties and page defaults
title: digitalbiostatistics
subtitle: 
description:  
header: images/banner3.png
footer: images/banner3.png
proofer: false
header-dark: false
footer-dark: false

languages:
  - code: en
    name: English
    home: /

  - code: zh
    name: 中文
    home: /zh/

  - code: es
    name: Español
    home: /es/

  - code: gl
    name: Galego
    home: /gl/

  - code: ar
    name: العربية
    home: /ar/
    direction: rtl

# site social media and other links
links:
  email: Marcos.Matabuena@mbzuai.ac.ae
  # orcid: 0000-0002-2764-5824
  google-scholar: qaEtbuEAAAAJ
  # github: digitalbiostatistics

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff

# configure jekyll spaceship
jekyll-spaceship:
  mathjax-processor:
    src:
      - https://cdn.jsdelivr.net/npm/mathjax@4/tex-mml-chtml.js
